### ISSUE TITLE
AriumwithSamples.unity package from beta version doesn't contain animation and scenes import packages

### ISSUE THREAD

**Issue by salingambhir01** [thoughtworks/Arium#9]
I have checked the beta version of Ariumwithsamples.unitypackage is missing. 

1. Animation
2. Scene folder
 in package,. when user tries to import AriumPackage. 
![missing animation and scene packages](https://user-images.githubusercontent.com/90327881/132515911-8c01b55f-5655-4af1-a379-befcd0a39425.png)

**Comment by Jayachandranaug29** [comment]
@salingambhir01  - There is a new package available with animations and scenes folder.

**Comment by Neelarghya** [comment]
Updated in the latest package v0.2.0
